# Generated by Django 5.0.3 on 2024-04-17 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0024_thitruong_ban_mota_thitruong_ban_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thitruong_ban',
            name='mota',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='thitruong_ban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
