# Generated by Django 5.0.2 on 2024-04-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0025_alter_thitruong_ban_mota_alter_thitruong_ban_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
