# Generated by Django 5.0.2 on 2024-04-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0027_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
