# Generated by Django 5.0.3 on 2024-04-26 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0029_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketName', models.CharField(max_length=200)),
                ('marketPlant', models.CharField(max_length=200)),
                ('marketFee', models.CharField(max_length=200)),
                ('marketDetail', models.CharField(max_length=1000)),
                ('marketUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='thitruong',
        ),
        migrations.DeleteModel(
            name='thitruong_ban',
        ),
    ]
