# Generated by Django 5.0.3 on 2024-04-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0031_remove_product_adress_product_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.AddField(
            model_name='product',
            name='adress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
