# Generated by Django 5.0.2 on 2024-05-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0032_remove_product_address_product_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_ND',
            field=models.CharField(help_text='Các khoáng chất cần thiết', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.adress'),
        ),
    ]
