# Generated by Django 5.0.2 on 2024-05-06 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0035_alter_notify_market_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify_market',
            name='link',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notify_market',
            name='customer',
        ),
        migrations.AddField(
            model_name='notify_market',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Manage.customer'),
            preserve_default=False,
        ),
    ]
