# Generated by Django 5.0.2 on 2024-05-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0036_notify_market_link_remove_notify_market_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify_market',
            name='timejoin',
            field=models.DateTimeField(),
        ),
    ]
