# Generated by Django 5.0.2 on 2024-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0037_alter_notify_market_timejoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify_market',
            name='is_read_trader',
            field=models.BooleanField(default=0),
        ),
    ]
