# Generated by Django 5.0.3 on 2024-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0038_notify_market_is_read_trader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('plant_pH_min', models.DecimalField(decimal_places=1, help_text='Độ pH tối thiểu', max_digits=2)),
                ('plant_pH_max', models.DecimalField(decimal_places=1, help_text='Độ pH tối đa', max_digits=2)),
                ('plant_DoAm_min', models.IntegerField(help_text='Độ ẩm tối thiểu')),
                ('plant_DoAm_max', models.IntegerField(help_text='Độ ẩm tối thiểu')),
            ],
        ),
    ]
