# Generated by Django 5.0.3 on 2024-05-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0039_plant_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.plant_mode'),
        ),
    ]
