# Generated by Django 5.0.3 on 2024-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0040_alter_plant_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(max_length=200),
        ),
    ]
